model: densenet169      # densenet169, resnet18, resnet50

data:
  # mean ,std & size from ImageNet pretrain
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  size: [224, 224]

  test: ~
  num_class: 2

weight: "densenet169.pth"
save: 
  path: results

# wandb:
#   project: ~
#   name: ~
#   resume_id: ~