# Support model:
# vgg16 | vgg19 | vgg16_bn | vgg19_bn
# densenet169 | densenet201
# resnet18 | resnet50 | resnet152
# convnext_base | convnext_large | convnext_small | convnext_tiny
model: 
  name: vgg16
  classifier: softmax # softmax, sigmoid

data:
  # mean ,std & size from ImageNet pretrain
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  size: [224, 224]
  batch: 16

  test: drafts/data/face_occlusion/Test
  num_class: 2

weight: "/media/lamkser/Lam Kser/Code/face-occlusion-classification/experiment/softmax/vgg16/last_vgg16.pth"
save: 
  path: results

# wandb:
#   project: ~
#   name: ~
#   resume_id: ~